//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class newCvEntities : DbContext
    {
        public newCvEntities()
            : base("name=newCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLILETISIM> TBLILETISIM { get; set; }
        public virtual DbSet<TBLİŞİM> TBLİŞİM { get; set; }
        public virtual DbSet<TBLJOP> TBLJOP { get; set; }
        public virtual DbSet<TBLPROJE> TBLPROJE { get; set; }
        public virtual DbSet<TBLSKILL> TBLSKILL { get; set; }
        public virtual DbSet<TBLYORUM> TBLYORUM { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
    }
}
