//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLJOP
    {
        public int ID { get; set; }
        public string ROL { get; set; }
        public string SIRKET { get; set; }
    }
}
